server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:authz.pub
          audiences: cashcard-client #  ensure that each JWT contains an aud claim with a value of cashcard-client.

logging:
  level:
    org.springframework.security: TRACE
